services:
  acervoapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acervoapi
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://acervo-database.clgawswe81nt.sa-east-1.rds.amazonaws.com/acervo
      - DATASOURCE_USERNAME=acervo_master
      - DATASOURCE_PASSWORD=acervomaster123!
      - GOOGLE_CLIENT_ID=client_id
      - GOOGLE_CLIENT_SECRET=client_secret
      - SPRING_PROFILES_ACTIVE=default
      - TZ=America/Sao_Paulo
      - MERCADO_PAGO_TOKEN:TEST-6817096861883625-052120-fafb78569ec128ca185d5f86b9cee0a9-594803070

volumes:
  postgres_data: